### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: '/usr/local/etc/privoxy/CA/trustedCAs.pem'

### ISSUE THREAD

**Issue by jrballesteros05** [Tardo/docker-privoxy-https#1]
Hello people from this docker project. I was trying to run the docker via docker-compose and I got this error

> Attaching to privoxy
privoxy  | Traceback (most recent call last):
privoxy  |   File "/usr/local/bin/privman", line 227, in <module>
privoxy  |     update_trusted_ca()
privoxy  |   File "/usr/local/bin/privman", line 29, in update_trusted_ca
privoxy  |     urllib.request.urlretrieve('https://curl.se/ca/cacert.pem', trusted_ca_file)
privoxy  |   File "/usr/lib/python3.11/urllib/request.py", line 251, in urlretrieve
privoxy  |     tfp = open(filename, 'wb')
privoxy  |           ^^^^^^^^^^^^^^^^^^^^
privoxy  | PermissionError: [Errno 13] Permission denied: '/usr/local/etc/privoxy/CA/trustedCAs.pem'
privoxy exited with code 0

I guess there is a permission issue somewhere in the Dockerfile. I tried running the docker manually but I get the same issue. 

Best regards.

**Comment by Tardo** [comment]
Hi! Can you give more details?
